name: CI

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

permissions:
  contents: read
  packages: read

jobs:
  ci:
    name: Validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: ./.github/actions/node-setup
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@studnicky'

      - name: Run CI checks
        run: pnpm run ci
